### ISSUE TITLE
TGS流程是否适用于lsf集群系统

### ISSUE THREAD

**Issue by jwli-code** [starskyzheng/panpop#55]
郑博士你好，在使用集群系统想大批量运行TGS进行处理的时候遇到报。 之前能用此方法跑其它的snakefile文件，但是这次的snakefile文件运行不成功，不知道哪里有问题。十分感谢
这是我的运行命令
`snakemake --profile lsf -j 100 --reason --printshellcmds -s Snakefile_TGS`
这是log文件
```
[Mon May 20 17:41:33 2024]
rule SVIM_asm_call_1_map:
    input: Ref.fa, /public/home/jwli/software/panpop/example/example_long_reads/s2.fa
    output: 03_vcf/06_SVIM_asm/s4/1.minimap.bam
    log: logs/2.s4.SVIM_asm.1.minimap2.log
    jobid: 118
    reason: Missing output files: 03_vcf/06_SVIM_asm/s4/1.minimap.bam
    wildcards: sample=s4
    threads: 20
    resources: mem_mb=20000


        /public/home/jwli/micromamba/envs/panpop/bin/minimap2 -a -x asm5 --cs -r2k -t 20 Ref.fa /public/home/jwli/software/panpop/example/example_long_reads/s2.fa 2>>logs/2.s4.SVIM_asm.1.minimap2.log | /public/home/jwli/micromamba/envs/panpop/bin/samtools view -b -o 03_vcf/06_SVIM_asm/s4/1.minimap.bam - 2>>logs/2.s4.SVIM_asm.1.minimap2.log

Traceback (most recent call last):
  File "/public/home/jwli/.config/snakemake/lsf/lsf_submit.py", line 230, in submit
    external_job_id = self._submit_cmd_and_get_external_job_id()
  File "/public/home/jwli/.config/snakemake/lsf/lsf_submit.py", line 216, in _submit_cmd_and_get_external_job_id
    output_stream, error_stream = OSLayer.run_process(self.submit_cmd)
  File "/public/home/jwli/.config/snakemake/lsf/OSLayer.py", line 41, in run_process
    cmd, check=True, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/public/home/software/opt/bio/software/Python/3.6.5/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bsub -M 20000 -n 20 -R 'select[mem>20000] rusage[mem=20000] span[hosts=1]' -o "logs/cluster/SVIM_asm_call_1_map/sample=s4/jobid118_381e1885-082f-41fe-9070-acbf31fd5b7f.out" -e "logs/cluster/SVIM_asm_call_1_map/sample=s4/jobid118_381e1885-082f-41fe-9070-acbf31fd5b7f.err" -J "SVIM_asm_call_1_map.sample=s4" -q normal /public/home/jwli/software/panpop/example/example_long_reads/.snakemake/tmp._p5aetht/snakejob.SVIM_asm_call_1_map.118.sh' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/jwli/.config/snakemake/lsf/lsf_submit.py", line 259, in <module>
    lsf_submit.submit()
  File "/public/home/jwli/.config/snakemake/lsf/lsf_submit.py", line 236, in submit
    raise BsubInvocationError(error)
__main__.BsubInvocationError: Command 'bsub -M 20000 -n 20 -R 'select[mem>20000] rusage[mem=20000] span[hosts=1]' -o "logs/cluster/SVIM_asm_call_1_map/sample=s4/jobid118_381e1885-082f-41fe-9070-acbf31fd5b7f.out" -e "logs/cluster/SVIM_asm_call_1_map/sample=s4/jobid118_381e1885-082f-41fe-9070-acbf31fd5b7f.err" -J "SVIM_asm_call_1_map.sample=s4" -q normal /public/home/jwli/software/panpop/example/example_long_reads/.snakemake/tmp._p5aetht/snakejob.SVIM_asm_call_1_map.118.sh' returned non-zero exit status 255.
Error submitting jobscript (exit code 1):
```

**Comment by jwli-code** [comment]
软件能否并行作业 跨节点跑？

**Comment by starskyzheng** [comment]
可以，snakemake原生支持的
